import type { Metadata } from "next";
import "./globals.css";
import {
	geistSans,
	geistMono,
	beVietnamPro,
	recoletaMedium,
	recoletaAltThin,
	recoletaAltSemiBold,
	recoletaSemiBold,
} from "@/lib/fonts";
import Footer from "@/_components/footer";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${recoletaMedium.variable} ${recoletaAltThin.variable} ${recoletaAltSemiBold.variable} ${recoletaSemiBold.variable} ${beVietnamPro.variable} font-be-vietnam-pro text-white dark:text-black antialiased`}
			>
				{/* <SiteHeader /> */}
				{children}
				<Footer />
			</body>
		</html>
	);
}
