import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SiteHeader from "@/_components/site-header/site-header";
import {
	geistSans,
	geistMono,
	beVietnamPro,
	recoletaMedium,
	recoletaAltThin,
} from "@/lib/fonts";
import Footer from "@/_components/footer";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${recoletaMedium.variable} ${recoletaAltThin.variable} antialiased ${beVietnamPro.variable} font-be-vietnam-pro text-white dark:text-black`}
			>
				{/* <SiteHeader /> */}
				{children}
				<Footer />
			</body>
		</html>
	);
}
